[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
smartcontractkit-chainlink-evm = "0.3.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
